name: hepitrack
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+8

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: ^1.1.6
  reorderables: ^0.3.2
  image_picker: ^0.6.5
  esys_flutter_share: ^1.0.2
  path: ^1.6.4
  photo_view: ^0.9.2
  simple_animations: ^1.3.12
  provider: ^4.0.5
  sqflite: ^1.3.0
  multiselect_formfield: ^0.1.2
  firebase_core: ^0.4.4+3
  firebase_remote_config: ^0.3.0+3
  http: ^0.12.1
  connectivity: ^0.4.8+5
  webview_flutter: ^0.3.21
  package_info: ^0.4.0+18
  dio: ^3.0.9
  flutter_secure_storage: ^3.3.3
  flutter_colorpicker: ^0.3.4
  flutter_email_sender: ^3.0.1
  dynamic_theme: ^1.0.1
  flutter_phoenix: ^0.1.0
  shared_preferences: ^0.5.7+3
  charts_flutter: ^0.9.0
  intl: ^0.16.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tracking/food.png
    - assets/tracking/water_empty.png
    - assets/tracking/water_little.png
    - assets/tracking/water_half.png
    - assets/tracking/water_full.png
    - assets/tracking/symptom.png
    - assets/symptom/fever.png
    - assets/symptom/exhaustion.png
    - assets/symptom/pain.png
    - assets/symptom/cough.png
    - assets/symptom/leak.png
    - assets/symptom/poop.png
    - assets/symptom/skin.png
    - assets/symptom/other.png
    - assets/error.png
    - assets/user.png
    - assets/news.png
    - assets/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
